### ISSUE TITLE
萌新提问_(:з」∠)_

### ISSUE THREAD

**Issue by HazukiTUT** [nyaoouo/FFxivPythonCraft#4]
我打开main会显示
2021-01-11 00:13:09,543 - pymem - DEBUG - Process 1540 is being debugged
[TTS]	Load White list:{'finsih', 'terminate'}
Traceback (most recent call last):
  File "D:\FFxivPythonCraft-master\main.py", line 9, in <module>
    Server(
  File "D:\FFxivPythonCraft-master\core\Utils\HttpServer.py", line 37, in start
    if check(self.port) :raise Exception("Port is in used")
Exception: Port is in used
<<press enter to exit>>
这样一条，_(:з」∠)_跑去看了一眼代码好像也没啥问题……不知道该怎么解决（辛苦大佬了_(:з」∠)_）

**Comment by nyaoouo** [comment]
更新一下就行了

**Comment by HazukiTUT** [comment]
好了诶！谢谢大佬！
